find_path(LOOPFUNC_INCLUDE_DIR NAMES LoopFunc.h
  PATHS
  HINTS ${PROJECT_SOURCE_DIR}/lib/include
)

find_library(LOOPFUNC_LIBRARY NAMES LoopFunc
  PATHS
  HINTS ${PROJECT_SOURCE_DIR}/lib
)

IF (LOOPFUNC_INCLUDE_DIR AND LOOPFUNC_LIBRARY)
    SET(LOOPFUNC_FOUND TRUE)
ENDIF (LOOPFUNC_INCLUDE_DIR AND LOOPFUNC_LIBRARY)


list(APPEND CMAKE_MODULE_PATH ${PROJECT_SOURCE_DIR}/cmake)
